### ISSUE TITLE
Client disconnect when joining server, both having linkedstorage-1.1.0.jar

### ISSUE THREAD

**Issue by Katorone** [kyrptonaught/linkedstorage#1]
Both server and client start normally.
When the client tries to connect to the server, it gets disconnected immediately.  The server logs the following error:

> lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: net.kyrptonaught.linkedstorage.recipe.CopyDyeRecipe.method_8112()Ljava/lang/String;

**Comment by kyrptonaught** [comment]
Does this build fix the issue? 
[linkedstorage-1.1.1.jar.zip](https://github.com/kyrptonaught/linkedstorage/files/4126519/linkedstorage-1.1.1.jar.zip)

**Comment by Katorone** [comment]
It does!  I've also tested the crafting recipes and they work as well.
Thank you!
