### ISSUE TITLE
Handheld Storage doesn't open when aimed at Redstone Ore

### ISSUE THREAD

**Issue by Ayutac** [kyrptonaught/linkedstorage#11]
The Handheld storage doesn't open when in hand and right-click while the block aimed at is Redstone Ore. This should be corrected.

**Comment by kyrptonaught** [comment]
Vanilla prioritizes a block's right click action before the items right click action, I'm unsure how to fix this

**Comment by Ayutac** [comment]
Torches seem to have a higher priority than Redstone ore, but a lower one than chests. Maybe the answer's there somewhere?

**Comment by kyrptonaught** [comment]
Upon digging through the source code, the redstone ore activation method checks to see if the player is holding a place-able block and if so places it. Not much I can do about this without some mixins

**Comment by Ayutac** [comment]
Alright, it isn't really important. Just stood out as odd for me, but on the other hand Vanilla Minecraft don't really has activatable, non-block items except the weapons/tools. You can close this issue if you want.
