### ISSUE TITLE
Handheld Storage can be moved when opened

### ISSUE THREAD

**Issue by Ayutac** [kyrptonaught/linkedstorage#12]
The Handheld Storage can be moved in the inventory after it was opened, especially it can be put into the storage it is linked to. So basically it can be put into itself. This shouldn't be so. Please make the Handheld Storage unmovable when opened, like e.g. the backpacks from Inmis.

**Comment by kyrptonaught** [comment]
Fixed in 1.3.4, i'll post a build shortly on curseforge

**Comment by kyrptonaught** [comment]
Uploaded
