### ISSUE TITLE
Items stuck in chest

### ISSUE THREAD

**Issue by TimelapsedEon** [kyrptonaught/linkedstorage#14]
Ender pouches(storageitem) stored in an Ender chest(storagechest) can't be removed if the Ender chest is opened using an Ender pouch. Is this intentional?

**Comment by kyrptonaught** [comment]
When using a pouch you are prevented from putting it into the chest, but it seems like it's also preventing you from removing it from the chest. I'll investigate

**Comment by kyrptonaught** [comment]
This has been fixed in 1.3.9, really sorry about the delay, i completely forgot about this
