### ISSUE TITLE
Cannot Place Handheld Storage A into Handheld Storage B

### ISSUE THREAD

**Issue by rxay579** [kyrptonaught/linkedstorage#15]
I think the fix here (https://github.com/kyrptonaught/linkedstorage/issues/12) caused all handheld storages in a player's inventory to be locked when one is open, regardless of whether they match the color pattern of the opened storage.

This result is not being able to place any handheld storage inside another, but I'm not sure if that was intentional.

**Comment by kyrptonaught** [comment]
This has been fixed in 1.3.9
