### ISSUE TITLE
Client Crash on Clicking GUI of Linked Storage Handheld with Block

### ISSUE THREAD

**Issue by rxay579** [kyrptonaught/linkedstorage#16]
With a Handheld Storage open, if you hold a block/item, then click the GUI borders (e.g. not inside a slot or outside the GUI to drop the item), the client crashes.  Doesn't seem to happen with a Linked Storage chest.
On a multiplayer server, the server itself doesn't crash and the block is dropped from the player's inventory as it can be found in the world by other players or when the client launches and reconnects.

Noticed on a private server with MC v1.16.1 with Linked Storage 1.3.6 and many other mods.
Tested with fresh MultiMC instance with MC v1.16.1 with Linked Storage 1.3.6, Fabric API v0.17.0b386, Fabric Loader v0.9.2b206.
Tested also in MC v1.16.2 with Linked Storage 1.3.8, Fabric API v0.20.1b401, Fabric Loader v0.9.2b206.

Crash logs from test instances:
LS 1.3.6 
[crash-2020-09-20_21.12.03-client.txt](https://github.com/kyrptonaught/linkedstorage/files/5253222/crash-2020-09-20_21.12.03-client.txt)
[latest.log](https://github.com/kyrptonaught/linkedstorage/files/5253223/latest.log)

LS 1.3.8
[crash-2020-09-20_21.13.31-client.txt](https://github.com/kyrptonaught/linkedstorage/files/5253217/crash-2020-09-20_21.13.31-client.txt)
[latest.log](https://github.com/kyrptonaught/linkedstorage/files/5253224/latest.log)

**Comment by kyrptonaught** [comment]
Wow I'm amazed this hasn't popped up until now, I apologize for the inconvenience. I've got a fix for it already, would you like me to back port to1.16.1?

**Comment by kyrptonaught** [comment]
This has been released as 1.3.9

**Comment by rxay579** [comment]
I didn't notice it myself until I started getting sloppy with where I clicked, then checked into it.
I would appreciate a back-port to 1.16.1 if it's not too much trouble.

**Comment by kyrptonaught** [comment]
Sorry for the delay, I may or may not have forgotten :P
https://www.curseforge.com/minecraft/mc-mods/linked-storage/files/3066415
