### ISSUE TITLE
1.16 Snapshot Update

### ISSUE THREAD

**Issue by AlasEyrd** [kyrptonaught/linkedstorage#2]
LinkedStorage crashes on launch in the 1.16 snapshot 20w06a.

Crash log from the whole modpack: https://paste.ee/p/z2vfu
Crash log from only Fabric API and LinkedStorage: https://paste.ee/p/LTstV

**Comment by kyrptonaught** [comment]
This is actually a crash from cardinal components, one of the libraries linkedstorage relies on. I’m working on a partial rewrite to not use cardinal components, instead making use of a custom system. Thank you for the report

**Comment by kyrptonaught** [comment]
I've got a beta build ready for testing if you would like to give it a shot, should be ready for release once I've confirmed there's no issues 
Note:
- This build will not transfer any inventories from the 1.15 version, this is planned before release. Keep in mind that your old inventories are subject to being lost loading a world with this version
- There's always a chance of losing inventories during the beta testing period, though I'm pretty happy with the saving/loading procedure so it most likely wont be happening

If you've made it this far: 
[linkedstorage-1.2.0.zip](https://github.com/kyrptonaught/linkedstorage/files/4179558/linkedstorage-1.2.0.zip)

**Comment by AlasEyrd** [comment]
Appears to work fine in my test world! I'm not updating anything, just putting together a snapshot modpack for myself and friends.
Thanks!
