### ISSUE TITLE
Resource Pack Guide

### ISSUE THREAD

**Issue by Merith-TK** [kyrptonaught/linkedstorage#22]
How did you achieve bundling a resource pack in your mod? I tried putting my resource pack in the same location, but it didnt work.

**Comment by kyrptonaught** [comment]
Ah I never pushed the most recent commit. I'll link to the part of the source here once I do

**Comment by kyrptonaught** [comment]
See here: https://github.com/kyrptonaught/linkedstorage/blob/e849538709bee51bf2db8797a46146635c6091dd/src/main/java/net/kyrptonaught/linkedstorage/LinkedStorageModClient.java#L52
