### ISSUE TITLE
Game crashed whilst initializing game

### ISSUE THREAD

**Issue by cursinorock** [kyrptonaught/linkedstorage#26]
[crash-2021-08-24_20.46.50-client.txt](https://github.com/kyrptonaught/linkedstorage/files/7042675/crash-2021-08-24_20.46.50-client.txt)

Fabric-api-0.39.1+1.17.jar.

Fabric 1.17.1

Server side works just fine.

**Comment by ThisIsWicked** [comment]
Same issue for me, pretty much identical crash log

**Comment by kyrptonaught** [comment]
This was fixed in 1.3.13
