### ISSUE TITLE
Chest Color Combination Issue

### ISSUE THREAD

**Issue by Kammon** [kyrptonaught/linkedstorage#29]
Hi there,

In the 1.18 Fabric release, I'm experiencing a glitch where if 2 or more storage blocks use the same 3 colors, but the middle and right color are transposed (ie Black/Blue/Orange and Black/Orange/Blue), the storages link up. This cuts the number of available channels down a good bit.

I'm playing on 1.18.1, and for testing I limited my mod set to just the Fabric API, Cloth-Config, Architectuary, Roughly Enough Items, and of course Linked Storage.

Thanks for your time!

**Comment by kyrptonaught** [comment]
I apologize for the VERY late response.

I am amazed that this has not been discovered yet. I see how this happens.

I'll try to find a fix without completely wiping old inventories

**Comment by kyrptonaught** [comment]
This has been fixed
