### ISSUE TITLE
piston attempting to move chest crashes game

### ISSUE THREAD

**Issue by obesevran** [kyrptonaught/linkedstorage#3]
this only happens when tile entities are made moveable ,but would add many many options if able. one of my fav mods thanks for bringing back

**Comment by kyrptonaught** [comment]
What mod are you using to make them mpovable?

**Comment by obesevran** [comment]
carpet mod moveable tile entities set to true.
________________________________

**Comment by kyrptonaught** [comment]
This has been fixed in 1.1.2
