### ISSUE TITLE
[Feature Request] Quick Shulker compatibility

### ISSUE THREAD

**Issue by Nataly171** [kyrptonaught/linkedstorage#31]
[Quick Shulker](https://www.curseforge.com/minecraft/mc-mods/quick-shulker) is a mod that allows you to open, among other things, shulker boxes and ender chests directly from your inventory, without even needing them in the hotbar. I think this mod would work well with that, allowing the Handheld Storage item to be opened in a similar way.

**Comment by kyrptonaught** [comment]
Quickshulker is actually a mod that I have made. I'm really surprised I didn't do this early.

The Handheld Storage Item now has support for Quickshulker
