### ISSUE TITLE
1.20 sometimes crashing while trying to place a Linked Storage

### ISSUE THREAD

**Issue by Nydaleclya** [kyrptonaught/linkedstorage#35]
[crash-2023-06-17_15.21.40-client.txt](https://github.com/kyrptonaught/linkedstorage/files/11779095/crash-2023-06-17_15.21.40-client.txt)

[crash-2023-06-17_15.36.45-client.txt](https://github.com/kyrptonaught/linkedstorage/files/11779126/crash-2023-06-17_15.36.45-client.txt)

**Comment by kyrptonaught** [comment]
This has been fixed
