### ISSUE TITLE
Cannot Redye my Chest White

### ISSUE THREAD

**Issue by CrankySupertoon** [kyrptonaught/linkedstorage#4]
**Mod Version:** 1.1.1
**MC Version:** 1.15.2

**What Happens:**
I want to revert one of my chests back to White White White and the Bonemeal is clearly refusing to work.

**What Do you Expect to Happen:** For it to dye the chest white.

Every other dye seems to work fine i think im either being an idiot or its a bug

**Comment by obesevran** [comment]
you turn bone meal into white dye
________________________________

**Comment by CrankySupertoon** [comment]
What mod does that crap or is that a vanilla thing also you can close this
