### ISSUE TITLE
Crash when multi player open same storage and take item

### ISSUE THREAD

**Issue by ahkui** [kyrptonaught/linkedstorage#6]
[crash-2020-03-13_14.39.05-server.txt](https://github.com/kyrptonaught/linkedstorage/files/4330096/crash-2020-03-13_14.39.05-server.txt)

**Comment by ahkui** [comment]
[crash-2020-03-13_15.10.32-server.txt](https://github.com/kyrptonaught/linkedstorage/files/4330222/crash-2020-03-13_15.10.32-server.txt)

**Comment by kyrptonaught** [comment]
Wow I’m really surprised this issue went unnoticed for this long. I know what’s wrong. I’ll try to get a fix out tomorrow

**Comment by ahkui** [comment]
Maybe other user only use on single player

**Comment by kyrptonaught** [comment]
Does this fix it? I'll bundle this into my next release if it does
[linkedstorage-1.1.3.zip](https://github.com/kyrptonaught/linkedstorage/files/4341713/linkedstorage-1.1.3.zip)

**Comment by ahkui** [comment]
I will try tonight

**Comment by ahkui** [comment]
my server is can't startup after use v1.1.3

[Here is the crash.log](https://github.com/kyrptonaught/linkedstorage/files/4350426/crash.log)

**Comment by kyrptonaught** [comment]
This should be properly fixed now
https://www.curseforge.com/minecraft/mc-mods/linked-storage/files/2911260

**Comment by ahkui** [comment]
It's still same here is the crash report 

[crash-2020-03-24_08.24.21-server.txt](https://github.com/kyrptonaught/linkedstorage/files/4374066/crash-2020-03-24_08.24.21-server.txt)

**Comment by kyrptonaught** [comment]
Ah it seems to be two separate instances of the same issue. I’ll fix it tomorrow

**Comment by ahkui** [comment]
okay.

**Comment by kyrptonaught** [comment]
Try this one?

[linkedstorage-1.2.1.jar.zip](https://github.com/kyrptonaught/linkedstorage/files/4382717/linkedstorage-1.2.1.jar.zip)

**Comment by ahkui** [comment]
it's work!
