### ISSUE TITLE
no comparator interaction 

### ISSUE THREAD

**Issue by obesevran** [kyrptonaught/linkedstorage#7]
comparator doesnt read fill level

**Comment by kyrptonaught** [comment]
Interesting, never thought to test this. I’ll add support

**Comment by kyrptonaught** [comment]
Hm so Ive got this implemented with a slight issue. The storage blocks do not automatically update when the inventory is changed by another storage block, this causes the comparators output to not change until it receives a block update. A work around could be automatically updating all instances of the storage blocks when the inventory is changed, which could cause a lot of lag if you have a lot of chests with a quick changing inventory. For now i'm just going to leave it be, but you will need to supply the comparator a block update in order for it to get a correct reading every so often

**Comment by obesevran** [comment]
Understood won't be a problem and I think that is a good way to do it.
________________________________
