### ISSUE TITLE
Player bound

### ISSUE THREAD

**Issue by TheUntamed** [kyrptonaught/linkedstorage#8]
Is it possible to make a linked Storage player bound in the mod version for mc 1.15.2? Just like Diamond on the knob in 1.12.2

**Comment by kyrptonaught** [comment]
It is actually completely implemented in the backend, I just haven’t gotten around to implementing the ability for the player to use it. Should be coming shortly

**Comment by TheUntamed** [comment]
Great news :)

**Comment by TheUntamed** [comment]
Another question: Is an Ender Tank planned?

**Comment by kyrptonaught** [comment]
Yes as well, but fabric does not currently have a standard fluid api. Everything out there uses their own implementation, I don’t want to manually add support for every single one. Once a standard is adopted, then I’ll implement an endertank

**Comment by TheUntamed** [comment]
fabric ... that's sad.

**Comment by kyrptonaught** [comment]
Oh you didn’t know it was for fabric?

**Comment by TheUntamed** [comment]
no. I just saw the mod in the mod list in twitch app. The description didn't tell me if the chests are able to be player bound and without that feature it's not usable for a server. So I asked before I tried to integrate it.

But it's ok. I'm getting used to it. A lot of mods are not marked as fabric mods.

**Comment by kyrptonaught** [comment]
It is in the fabric category, and all the downloads are marked as compatible with the fabric loader. Twitch must not show those

**Comment by TheUntamed** [comment]
The problem is that the twitch app doesn't allow to search for Forge mods only. I can search specifically for fabric mods but not for forge mods. So I have to search for all mods.

**Comment by kyrptonaught** [comment]
Still fabric only, but this has been implemented in 1.3.0

**Comment by scribbler957** [comment]
This is still an issue. You need to mention it in the CF description. When I'm looking for Fabric mods I assume the author will actually say Fabric, but there isn't even a Fabric dependent listed under Relations.
